Html forms
DirCd/Tekwill-Begin pull request #3
Opened 2023-08-20 20:21 UTC by DirCd

![Screenshot_1](https://github.com/DirCd/Tekwill-Begin/assets/141740084/c8eca4d2-1f08-49bb-914d-f1c32bd099bf)

2023-08-21 09:15 UTC, IvanCeban requested changes

2023-08-21 09:15 UTC, IvanCeban commented on Forms.html
> +    <input type="reset">
reset input should have a value as well

2023-08-21 09:15 UTC, IvanCeban commented on Forms.html
> +        <label for="f-c">Feedback/Comments</label>
avoid using such id and names - "f-c". It is clear for you now in this part of code, but if you start using the id or name in an external CSS or JS file you will get lost. 
Always use meaningfully names, classes, ids

2023-08-21 09:15 UTC, IvanCeban commented on Forms.html
> +            <option value="adv">Advertisement</option>
c'mon, don't be lazy.
Write the word in full. Imagine that on backed will work somebody else and he doesn't understand what you mean by "adv"

2023-08-21 09:15 UTC, IvanCeban commented on Forms.html
> +        <input type="date" id="DOB" name="DOB">
no uppercase for id's.
Only lowercase or kebab-case / snake_case

2023-08-21 09:15 UTC, IvanCeban commented on Forms.html
> +            <option value="adv">Advertisement</option>
I mean not only this one. But all thee abbreviations you used in the rest of elements

2023-08-28 10:22 UTC, DirCd commented on Forms.html
> +    <input type="reset">
![image](https://github.com/DirCd/Tekwill-Begin/assets/141740084/046c5b14-8f6d-4f7f-84e5-7173b9d961b7)

2023-08-28 10:23 UTC, DirCd commented on Forms.html
> +        <label for="f-c">Feedback/Comments</label>
![image](https://github.com/DirCd/Tekwill-Begin/assets/141740084/cd5b3917-a990-494d-bb6f-9e11ff455c8e)

2023-08-28 10:33 UTC, closed without merging